export const FETCH_QUESTION_CATAGORIES = 'FETCH_QUESTION_CATAGORIES';
export const FETCH_QUESTION_TAGS = 'FETCH_QUESTION_TAGS';
export const FETCH_QUESTION_ALL = 'FETCH_QUESTION_ALL';
export const FETCH_ARTICLE_CATAGORIES = 'FETCH_ARTICLE_CATAGORIES';
export const FETCH_ARTICLE_TAGS = 'FETCH_ARTICLE_TAGS';
export const FETCH_ARTICLE_ALL = 'FETCH_ARTICLE_ALL';
